### ISSUE TITLE
Git permission issue with samba ad docker

### ISSUE THREAD

**Issue by codedev900** [instantlinux/docker-tools#100]
I have that samba AD docker image running and all the files are owned by the root user. The issue is when I tire to push it to a git repo, I get a lost of permissions issues. I know samba AD needs root to write, but is there a way to get pushed to git repo without sudo?

**Comment by instantlinux** [comment]
I do not understand the use-case. Why does `git push` need to run in a docker image running samba-dc?

**Comment by codedev900** [comment]
Issue was not related to `git push`
