### ISSUE TITLE
Adding samba-winbind-clients to allow access to ntlm_auth for mschapv2 authentication

### ISSUE THREAD

**Issue by andrin55** [instantlinux/docker-tools#103]
The tool "ntlm_auth", provided in "samba-winbind-clients" is necessary to allow NTLM authentication by external programs.

One such exameple is FreeRadius: https://wiki.freeradius.org/guide/FreeRADIUS-Active-Directory-Integration-HOWTO#introduction_mods-available-mschap

**Comment by instantlinux** [comment]
Do a `docker pull` of `instantantlinux/samba-dc:4.16.8-r0` to pick up this update.

**Comment by andrin55** [comment]
Thank you
