### ISSUE TITLE
Failed to listen on 0.0.0.0:135 - NT_STATUS_ADDRESS_ALREADY_ASSOCIATED

### ISSUE THREAD

**Issue by codedev900** [instantlinux/docker-tools#110]
Starting the docker container I got this error "service_setup_stream_socket(address=::,port=135) for epmapper mgmt failed - NT_STATUS_ADDRESS_ALREADY_ASSOCIATED". Port 135 is used by RPC Endpoint Mapper service in Windows. Any way to disable port 135 in the docker container?

**Comment by instantlinux** [comment]
Port 135 is among those defined by the [samba docs|https://wiki.samba.org/index.php/Samba_AD_DC_Port_Usage]. It cannot be disabled. The instantlinux/samba-dc container must be run (under a Linux host) with `network: host`. Host network mode is unsupported by Docker under a Windows host. So I assume that another service has already grabbed port 135: use `netstat -antp|grep 135` to see what process ID is attached to port 135; stop that process before running the samba-dc container.
