### ISSUE TITLE
nut-upsd healthcheck does not work

### ISSUE THREAD

**Issue by Alarez777** [instantlinux/docker-tools#119]
The healthcheck does not work in the nut-upsd container when the NAME environment variable is changed. It seems that the problem is in docker-tools/images/nut-upsd/dockerfile in this line because the $NAME variable is not considered:
HEALTHCHECK CMD upsc ups@localhost:3493 2>&1|grep -q stale && exit 1 || true

**Comment by instantlinux** [comment]
This fix is now available, please pull the `latest` or `2.8.0-r4` tag.
