### ISSUE TITLE
ldap server require strong auth no persistence 

### ISSUE THREAD

**Issue by docfactory37** [instantlinux/docker-tools#135]
Hi, 

I'm trying to set the blow in the smb.conf but when I do a docker restart for the config to apply it removes it from the config file

ldap server require strong auth = no

**Comment by instantlinux** [comment]
Did you follow the [README](https://github.com/instantlinux/docker-tools/blob/main/images/samba-dc/README.md)? It states that you should put configuration into new files under a mount point, rather than trying to edit `smb.conf`.

> If you need further customizations, put them in one or more files under mount point /etc/samba/conf.d.

**Comment by docfactory37** [comment]
Hi, 

Sorry no I missed that 😞

I will have a proper read though 

thank you in advance
