### ISSUE TITLE
Error on start up of nut upsd container

### ISSUE THREAD

**Issue by nicxvan** [instantlinux/docker-tools#15]
This error is in the logs when starting the container.

```
fopen /var/run/nut/upsd.pid: No such file or directory
```

**Comment by instantlinux** [comment]
This is an innocuous error; after some experimenting, I found that the message you get if pid file contains a 0 is less misleading:
```
https://github.com/instantlinux/docker-tools/pull/16
```
So I've updated the image to give that message instead. Thanks for making note of this, it'll be less confusing for other users.
