### ISSUE TITLE
weewx: volumes bind for persistent data

### ISSUE THREAD

**Issue by pbartko** [instantlinux/docker-tools#30]
I am using your latest weewx docker image from Dockerhub but have run into a problem trying to bind volumes for persistent data.  I was successful in binding /secrets folder for passwords to my host system. However when I bind the /home/weewx folder to my host system, the docker won't run.  I've attached the log file here:
[weewx log2.txt](https://github.com/instantlinux/docker-tools/files/4217098/weewx.log2.txt)

Any help is much appreciated.

Thanks,

Pete

**Comment by instantlinux** [comment]
The /home/weewx folder has the application code in it. You could mount specific files within it if you want to add or override those in the container, but the code needs to be available in order to run.

**Comment by instantlinux** [comment]
Please reopen if you have further questions.
