### ISSUE TITLE
samba: pls provide image for raspberry pi (arm32)

### ISSUE THREAD

**Issue by c64emulator** [instantlinux/docker-tools#31]
Hi,
I use already the instantlinux/nut-upsd-arm32 for the raspberry pi.
Thanx  a lot for your great work.
I would appreciate a build of samba for the raspberry pi.

**Comment by instantlinux** [comment]
See new images:
https://hub.docker.com/repository/docker/instantlinux/samba-arm32
https://hub.docker.com/repository/docker/instantlinux/samba-arm64

Initial tagged version of each is 4.11.5-r0.

Let me know how these work for you.

**Comment by instantlinux** [comment]
I've now published the main image (and over a dozen others) using multi-arch manifests. See the README file for instantlinux/samba:
https://hub.docker.com/repository/docker/instantlinux/samba
