### ISSUE TITLE
samba-dc uses realm as for path without lowercasing it

### ISSUE THREAD

**Issue by dafzor** [instantlinux/docker-tools#42]
Samba creates the realm path in lowercase only, if REALM environment has any capitalization the NETLOGON folder will not be accessible.

**Comment by instantlinux** [comment]
Added the following line to [entrypoint.sh](https://github.com/instantlinux/docker-tools/blob/master/images/samba-dc/entrypoint.sh) starting with version 4.12.6-r0:
```
REALM=$(echo "$REALM" | tr [A-Z] [a-z])
```
Thanks for pointing this out. The REALM variable should be specified as a lowercase FQDN but some users may prefer capitalization.
