### ISSUE TITLE
samba-dc documentation on WORKGROUP is misleading

### ISSUE THREAD

**Issue by dafzor** [instantlinux/docker-tools#43]
When creating a domain with samba, WORKGROUP is not the workgroup but the legacy name of the domain.

A better description would be "Short name of the domain, used DOMAIN\username logins" with default "AD" to match default REALM.

**Comment by instantlinux** [comment]
Changed the default from WORKGROUP to AD, as you suggest. Tried in vain to find current doc for this value in the samba.org wiki; updated the [README](https://github.com/instantlinux/docker-tools/tree/master/images/samba-dc#variables) to describe it as _realm prefix_ and note that it's poorly documented.
