### ISSUE TITLE
samba-dc documentation could suggest an alternative to docker secret

### ISSUE THREAD

**Issue by dafzor** [instantlinux/docker-tools#45]
Docker secrets are only available when working in a swarm.

However when using the container on a simple docker host it's easier to bind a file to /run/secrets/${ADMIN_PASSWORD_SECRET} on the container.

The documentation could suggest that as an alternative to using docker secret.

**Comment by instantlinux** [comment]
Added a note to the Secrets section of [README|https://github.com/instantlinux/docker-tools/tree/master/images/samba-dc] with a link to the already-existing example. Thanks for pointing out this doc error!
