### ISSUE TITLE
nut-upsd: 'Permission denied' error when using custom upsd.users

### ISSUE THREAD

**Issue by watson81** [instantlinux/docker-tools#75]
In the NUT docker image, when using a custom `upsd.users` file mounted in `/etc/nut/local/upsd.users`, the following error is emitted on startup:
> Can't open /etc/nut/upsd.users: Permission denied

**Comment by instantlinux** [comment]
Entrypoint now does this at startup:
```
chgrp $GROUP /etc/nut/*
chmod 640 /etc/nut/*
```
Thanks for your report!
