### ISSUE TITLE
Vsftpd segfault workaround

### ISSUE THREAD

**Issue by kovacsbalu** [instantlinux/docker-tools#8]
Probably fixed with this commit: [InfrastructureServices/vsftpd](https://github.com/InfrastructureServices/vsftpd/commit/970711fde95bee3de1e4a5e0b557c3132d0c3e3f) or simply remove exec from `entrypoint.sh`.

**Comment by instantlinux** [comment]
I've pushed your workaround (removed the exec) to tag 3.0.3-r5 in [instantlinux/vsftpd](https://hub.docker.com/r/instantlinux/vsftpd). Thanks for the suggestion.
