### ISSUE TITLE
nut-upsd

### ISSUE THREAD

**Issue by shadoskill** [instantlinux/docker-tools#91]
Network UPS Tools - Generic HID driver 0.47 (20220715-1526-gded7a4cdc7)
Failed to init libusb 1.0: No such file or directory
USB communication driver (libusb 1.0) 0.43
Driver failed to start (exit status=1)

Rasbery Pi 4 64bit Raspbian

**Comment by instantlinux** [comment]
See line 13 of [docker-compose.yml](https://github.com/instantlinux/docker-tools/blob/2a172f2b4476c1110c5c2007c6463fadec7a9c58/images/nut-upsd/docker-compose.yml#L13] or line 6 of [values.yaml](https://github.com/instantlinux/docker-tools/blob/2a172f2b4476c1110c5c2007c6463fadec7a9c58/images/nut-upsd/helm/values.yaml#L6) in the provide helm chart for example of setting privileged mode.
